### ISSUE TITLE
Changing lucene index target directory in docker container

### ISSUE THREAD

**Issue by borsosl** [hapifhir/hapi-fhir-jpaserver-starter#152] opened 2020-10-12 08:30 UTC
I'm trying to put data directories in a mounted location.

```
docker run -p 8080:8080 -v "c:/db/hapi:/mnt/storage" -e "spring.datasource.url=jdbc:h2:file:/mnt/storage/database/h2" -e "spring.jpa.properties.hibernate.search.default.indexBase=/mnt/storage/lucenefiles" hapiproject/hapi
```

The H2 database is created on the mounted path, but the hibernate search still defaults to 'target/lucenefiles', that is in root filesystem of the container:

```
2020-10-12 07:49:13.649 [main] INFO  o.h.s.s.impl.DirectoryProviderHelper [DirectoryProviderHelper.java:139] HSEARCH000041: Index directory not found, creating: 'target/lucenefiles'
2020-10-12 07:49:13.655 [main] INFO  o.h.s.s.impl.DirectoryProviderHelper [DirectoryProviderHelper.java:139] HSEARCH000041: Index directory not found, creating: 'target/lucenefiles/ca.uhn.fhir.jpa.model.entity.ResourceIndexedSearchParamString'
2020-10-12 07:49:13.959 [main] INFO  o.h.s.s.impl.DirectoryProviderHelper [DirectoryProviderHelper.java:139] HSEARCH000041: Index directory not found, creating: 'target/lucenefiles/ca.uhn.fhir.jpa.entity.TermConcept'
2020-10-12 07:49:13.993 [main] INFO  o.h.s.s.impl.DirectoryProviderHelper [DirectoryProviderHelper.java:139] HSEARCH000041: Index directory not found, creating: 'target/lucenefiles/ca.uhn.fhir.jpa.model.entity.ResourceTable'
```

Is there a way to change this with passed environment variables?

**Comment by ricardofago** [comment] 2020-10-14 02:14
Probably related to #150. Judging by https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/EnvironmentHelper.java, it looks like the `hibernate.search.default.indexBase` property is currently hardcoded.

**Comment by borsosl** [comment] 2020-10-14 11:28
Thank you. As a workaround I built my own docker image with the hardcoded value replaced.

**Comment by ftbe** [comment] 2020-11-13 15:20
The problem is that `EnvironmentHelper.getHibernateProperties()` expect the whole hibernate config to be stored in a space-delimited `String` under the key `spring.jpa.properties`.

It's not the case, each entry in the config is stored under its own key, something like `spring.jpa.properties.hibernate.search.default.indexBase` :
![image](https://user-images.githubusercontent.com/4537117/99087776-736c5380-25cb-11eb-9902-bd4c085586f0.png)

and there is nothing stored under the `spring.jpa.properties` key :

![image](https://user-images.githubusercontent.com/4537117/99087924-9eef3e00-25cb-11eb-812d-fd23f3de2af7.png)

Either ways, it's strange to have default values defined in the code.

**Comment by jkiddo** [comment] 2021-06-26 20:09
This has been fixed in the latest range of commits to EnvironmentHelper.

**Closed by jkiddo** 2021-06-26 20:09 UTC
