### ISSUE TITLE
Optimize slow request "select resourcesearchview"

### ISSUE THREAD

**Issue by nekrasoft** [hapifhir/hapi-fhir-jpaserver-starter#421] opened 2022-08-29 15:29 UTC
Hi, thanks for your hapi-fhir implementation.

We're using the latest version of fhir-service in our infrastructure. Everything is ok, but we've found one internal slow operation which turned out to be the common reason for several different api-requests. 
This operation is `iresourcesearchviewdao.findbyresourceids -> select resourcesearchview`
We've discovered it with the help of OpenTelemetry metrics visualized via Jaeger, see the screens below.

So our question is the following: is there any opportunity to refactor this operation to make it faster?
Can you point out some specific reasons for such slow execution of this operation? 

Thanks.

![slow-select-resourcesearchview](https://user-images.githubusercontent.com/68195/187235469-002d9d93-3090-439b-89ce-d355592d269d.png)

![fhir-long-endpoints](https://user-images.githubusercontent.com/68195/187236734-e658860f-dfdc-4578-8081-0a404f28fe8d.jpg)

**Comment by KevinDougan-SmileCDR** [comment] 2022-09-07 19:45
Hi there,

I believe you may need to investigate the database that you are using for possible performance issues.

Is it one of the supported databases?

https://hapifhir.io/hapi-fhir/docs/server_jpa/database_support.html

Is it in the same local network as your FHIR Server or is it in "the cloud" or on some other remote network?

More information would be required to determine the root cause of your performance issues.

Also, these types of questions are best asked in the Google Group, and not as an Issue in the project itself, so I will Close this Issue and request that you ask your question in the group:

https://groups.google.com/g/hapi-fhir

Thanks!
Kevin

**Closed by KevinDougan-SmileCDR** 2022-09-07 19:45 UTC

**Comment by jamesagnew** [comment] 2022-10-11 06:59
This is neat analysis, thanks for sharing.

That specific query path amounts to "load the resource bodies and metadata
for a collection of resource IDs", where the IDs were discovered in a
previous step. Effectively this points to you loading quite a bit of data
(as opposed to, say, performing an inefficient search where index
optimization might help). Do your use cases require you to fetch a large
number of resources? If not, using smaller page sizes might help?

Cheers,
James
