### ISSUE TITLE
Invalid response when using _summary=count

### ISSUE THREAD

**Issue by Legi429** [hapifhir/hapi-fhir-jpaserver-starter#88] opened 2020-03-16 12:04 UTC
Hi :)
I've been trying to have the server give me the total number of results for a given search. I noticed that the Bundle I get as a response does not include the `type` key which is required based on the FHIR standard:
https://www.hl7.org/fhir/bundle-definitions.html#Bundle.type

The most appropriate type appears to be "searchset". When I use _summary with all the other valid options, that's the type I get in the response.
Example of the problem:
`http://hapi.fhir.org/baseR4/Media?_summary=count` gives me:
```json
{
  "resourceType": "Bundle",
  "id": "9aaf1d79-4c1a-4c9c-a3db-ea5b119653b6",
  "meta": {
    "lastUpdated": "2020-03-16T12:02:17.484+00:00",
    "tag": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
        "code": "SUBSETTED",
        "display": "Resource encoded in summary mode"
      }
    ]
  },
  "total": 1705
}
```

I have created another issue here:
https://github.com/jamesagnew/hapi-fhir/issues/1763

**Comment by jamesagnew** [comment] 2020-03-16 15:35
Duplicate of https://github.com/jamesagnew/hapi-fhir/issues/1763 - Please don't open the same ticket in multiple repositories.

**Closed by jamesagnew** 2020-03-16 15:35 UTC
