### ISSUE TITLE
DockerBuild fails on mvn -ntp dependency:go-offline with Could not find artifact ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:jar:5.3.0 in oss-snapshots

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir-jpaserver-starter#214] opened 2021-02-26 11:55 UTC
Building the current docker image fails with

> 
> [WARNING] The project ca.uhn.hapi.fhir:hapi-fhir-jpaserver-starter:war:5.3.0 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
> [INFO] 
> [INFO] ------------< ca.uhn.hapi.fhir:hapi-fhir-jpaserver-starter >------------
> [INFO] Building HAPI FHIR JPA Server - Starter Project 5.3.0
> [INFO] --------------------------------[ war ]---------------------------------
> [INFO] 
> [INFO] --- maven-dependency-plugin:3.1.2:go-offline (default-cli) @ hapi-fhir-jpaserver-starter ---
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  03:30 min
> [INFO] Finished at: 2021-02-26T11:44:38Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline (default-cli) on project hapi-fhir-jpaserver-starter: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:jar:5.3.0 in oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> The command '/bin/sh -c mvn -ntp dependency:go-offline' returned a non-zero code: 1

starting the project with jetty works.
I wonder why maven is looking for the .jar. 
The repository only contains the .war as far was I can see.

Best
Patrick

**Comment by mendo-** [comment] 2021-03-03 16:40
I have been running into this same issue when trying to upgrade from v5.2.0 to v5.3.0

**Comment by ZuSe** [comment] 2021-03-03 16:58
Hi Mendo

I have removed for now the mvn offline task from the Dockerfile. In case that helps you and ur host/cluster has external internet access.

Best
Patrick

**Comment by jvitrifork** [comment] 2021-03-03 19:47
That weird ... I've run a lot of builds the last couple of days and haven't seen this at all

**Comment by ZuSe** [comment] 2021-03-03 20:35
@jvitrifork  Can you share your docker file or is it the default one? I think you are using a custom one with distroless as well, dont u?

**Comment by Koudysmen** [comment] 2021-03-05 11:08
@jvitrifork  I have been running into this same issue when trying to build this dockerfile.

```
FROM maven:3.6.3-jdk-11-slim as build-hapi
WORKDIR /tmp

ARG HAPI_FHIR_STARTER_URL=https://github.com/hapifhir/hapi-fhir-jpaserver-starter/
ARG HAPI_FHIR_STARTER_BRANCH=master

RUN apt-get update && apt-get install git -y
RUN git clone --branch ${HAPI_FHIR_STARTER_BRANCH} ${HAPI_FHIR_STARTER_URL} starter-clone

WORKDIR /tmp/hapi-fhir-jpaserver-starter

COPY pom.xml .
RUN mvn -ntp dependency:go-offline

RUN mv /tmp/starter-clone/src/ /tmp/hapi-fhir-jpaserver-starter/src/
RUN mvn clean install -DskipTests

FROM tomcat:9.0.38-jdk11-openjdk-slim-buster

RUN mkdir -p /data/hapi/lucenefiles && chmod 775 /data/hapi/lucenefiles
COPY --from=build-hapi /tmp/hapi-fhir-jpaserver-starter/target/*.war /usr/local/tomcat/webapps/ROOT.tmp

ENV BASE_URI "/ROOT"

EXPOSE 8080

CMD mv /usr/local/tomcat/webapps/ROOT.tmp /usr/local/tomcat/webapps${BASE_URI}.war && exec catalina.sh run
```

I also tried build default docker image but the result was same.
My hot fix :
1. Comments dependencies and plugin for "hapi-fhir-testpage-overlay" in pom.xml
2. Comment java class FhirTesterConfig.java
3. Comment FhirTesterConfig usages in Application.java

After these changes I am possible build image using default dockerfile but it isn't properly solution.

**Comment by jvitrifork** [comment] 2021-03-05 11:14
I have reproduced the error when using the default https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/Dockerfile 

I'll look into it

**Comment by jvitrifork** [comment] 2021-03-05 11:53
@jamesagnew, this one is related to 2ddee148c93d1a7433e20b7c17e2bfe79ccc3b38. I believe we historically primarily have depended on the snapshot version. Regardless, the error

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline (default-cli) on project hapi-fhir-jpaserver-starter: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:jar:5.3.0 in oss-snapshots
```
-is probably due to the fact that the overlay is not published as a stable to the snapshot repo (a bit wierd but whatever). I suggest that we either get the stable overlay released to the snapshot repo or depend on 5.4.0-SNAPSHOT which I don't believe have been released yet. @jamesagnew which would you prefer? The current setup has been using snapshot: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/c070429698b820d41724e4278b9a594368f30db5/pom.xml#L41

**Comment by mendo-** [comment] 2021-03-05 15:14
> @jvitrifork I have been running into this same issue when trying to build this dockerfile.
> 
> ```
> FROM maven:3.6.3-jdk-11-slim as build-hapi
> WORKDIR /tmp
> 
> ARG HAPI_FHIR_STARTER_URL=https://github.com/hapifhir/hapi-fhir-jpaserver-starter/
> ARG HAPI_FHIR_STARTER_BRANCH=master
> 
> RUN apt-get update && apt-get install git -y
> RUN git clone --branch ${HAPI_FHIR_STARTER_BRANCH} ${HAPI_FHIR_STARTER_URL} starter-clone
> 
> WORKDIR /tmp/hapi-fhir-jpaserver-starter
> 
> COPY pom.xml .
> RUN mvn -ntp dependency:go-offline
> 
> RUN mv /tmp/starter-clone/src/ /tmp/hapi-fhir-jpaserver-starter/src/
> RUN mvn clean install -DskipTests
> 
> FROM tomcat:9.0.38-jdk11-openjdk-slim-buster
> 
> RUN mkdir -p /data/hapi/lucenefiles && chmod 775 /data/hapi/lucenefiles
> COPY --from=build-hapi /tmp/hapi-fhir-jpaserver-starter/target/*.war /usr/local/tomcat/webapps/ROOT.tmp
> 
> ENV BASE_URI "/ROOT"
> 
> EXPOSE 8080
> 
> CMD mv /usr/local/tomcat/webapps/ROOT.tmp /usr/local/tomcat/webapps${BASE_URI}.war && exec catalina.sh run
> ```
> 
> I also tried build default docker image but the result was same.
> My hot fix :
> 
> 1. Comment dependencies and plugin for "hapi-fhir-testpage-overlay" in pom.xml
> 2. Comment java class FhirTesterConfig.java
> 3. Comment FhirTesterConfig usages in Application.java
> 
> After these changes I am possible build image using default dockerfile but it isn't properly solution.

This worked for me in the interim. Thanks

**Comment by jamesagnew** [comment] 2021-03-05 15:36
@jvitrifork I'm not sure I follow - The overlay 5.3.0 is in Maven central: https://repo1.maven.org/maven2/ca/uhn/hapi/fhir/hapi-fhir-testpage-overlay/5.3.0/

**Comment by jvitrifork** [comment] 2021-03-05 15:38
Yep, but the repo pointed to in the pom points to snapshot repos

**Comment by jvitrifork** [comment] 2021-03-05 15:40
So the question is: Would you like to have the starter project to point to stable resources and forget about snapshot - or would you like it as a testbed for the HAPI project itself by having it pointing at snapshots

**Comment by jamesagnew** [comment] 2021-03-05 15:41
Git `master` for the stable project should point to stable dependencies only. For this project we typically start a living PR and branch with a snapshot version at somepoint during the quarter, which hasn't happened yet this quarter.

**Comment by jamesagnew** [comment] 2021-03-05 15:42
I still don't understand the issue though.. Surely that snapshot repo in the pom shouldn't be an issue, or how would *any* of the hapi fhir libraries get pulled in? They're all non-snapshot versions too

**Comment by jvitrifork** [comment] 2021-03-05 15:48
found it - i think: 
```
#13 345.1 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline (default-cli) on project hapi-fhir-jpaserver-starter: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:jar:5.3.0 in oss-releases (https://oss.sonatype.org/content/repositories/releases/) -> [Help 1]
#13 345.1 [ERROR] 
```

The keyword here would be **jar** - not **war**

**Comment by jamesagnew** [comment] 2021-03-05 15:54
I don't believe we've ever published this dependency as a JAR, it's always had a type of war. There's no JAR at least in central, e.g. for 5.2.0: https://repo1.maven.org/maven2/ca/uhn/hapi/fhir/hapi-fhir-testpage-overlay/5.2.0/
..or in the current snapshot repo: https://oss.sonatype.org/content/repositories/snapshots/ca/uhn/hapi/fhir/hapi-fhir-testpage-overlay/5.4.0-PRE1-SNAPSHOT/

I wonder what's making it look for that...

**Comment by jamesagnew** [comment] 2021-03-05 16:36
I just tried it and sure enough, executing `mvn -ntp dependency:go-offline` fails for me with the same error.

I feel like this is a bug in the maven dependency plugin. We depend on the following:
```xml
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-testpage-overlay</artifactId>
            <version>${project.version}</version>
            <classifier>classes</classifier>
        </dependency>
```

It seems like it's ignoring the `<classifier>`.

**Comment by jamesagnew** [comment] 2021-03-05 16:39
Sure enough, downgrading that plugin to 3.1.1 solves the issue. This is a regression in Maven... yikes.

**Comment by jamesagnew** [comment] 2021-03-05 16:47
Workaround checked in. The underlying issue has been reported here:
https://issues.apache.org/jira/browse/MDEP-739

**Closed** 2021-03-05 16:47 UTC
